---
title: "Finite Graphs and Network Analysis"
output: html_notebook
author: Orville Hombrebueno
---

```{r}
library(igraph) # Load the igraph package
g1 <- graph( edges=c(1,2, 2,3, 3, 1), n=3, directed=F ) 
plot(g1) # A simple plot of the network 
```

```{r}
# Now with 10 vertices, and directed by default:

g2 <- graph(edges=c(2,2, 3,3, 3, 1), n=4 )

plot(g2) 
```

```{r}
g4 <- graph( c("John", "Jim", "Jim", "Jack", "Jim", "Jack", "John", "John"), 

             isolates=c("Jesse", "Janis", "Jennifer", "Justin") )  

# In named graphs we can specify isolates by providing a list of their names.



plot(g4, edge.arrow.size=.5, vertex.color="gold", vertex.size=15, 

     vertex.frame.color="gray", vertex.label.color="black",

     vertex.label.cex=0.8, vertex.label.dist=2, edge.curved=0.2) 
```

```{r}
g<-graph.full(n=5, directed = FALSE, loops = FALSE)

plot(g)
get.edgelist(g)
```


```{r}
edges <- c(1,2, 3,2, 2,4)
g<-graph(edges, n=max(edges), directed=TRUE)
plot(g)
```

```{r}
make_full_graph(5)
print_all(make_full_graph(4, directed = F))
```

<<<<<<< HEAD
```{r}
st <- make_star(10)
plot(st, vertex.size=5, vertex.label=NA)
```

