---
title: "**A Critique Paper on Essential Edge Connectivity of Line Graphs**"
author: |
  | **SAINT MARY'S UNIVERSITY**
  | Bayombong, Nueva Vizcaya
  | **School of Graduate Studies**
  |
  |
  | In Partial Fulfillment of the Requirements in
  | **Finite Graphs and Network Analysis**
  |
  |
  | Submitted by:
  | ORVILLE D. HOMBREBUENO
  | odhombrebueno@nvsu.edu.ph
  | 
  |
  | Submitted to:
  | PROFESSOR ANALYN GUEVARA
date: "May 27, 2020"
output: pdf_document
fontsize: 12pt
bibliography: connectivity.bib
csl: apa.csl
documentclass: article
---
\pagebreak
# Summary

The title of the article is **Essential Edge Connectivity of Line Graphs** by Yehong Shao. It has 3 parts: 1) introduction, 2) preliminary results and 3) proof of main theorem 1.3.

In the introduction, the author first introduced the concept of the line graph of a simple graph $G$ denoted by $L(G)$ and how it is constructed with respect to $G$. The author then continued to discuss some basic notations such as the degree of a vertex $v\in V(G)$, $d_{G}(v)$ or $d(v)$, the minimum degree of $G$, $\delta(G)$, the edge connectivity of $G$, $\kappa^{'}(G)$, and the vertex connectivity of $G$, $\kappa(G)$. The inequality $\delta(L(G))\geq 2\delta(G)-2$ (by definition of a line graph is a property introduced by @chartrand69 who are pioneers in the study of connectivity and edge connectivity relations of a graph and its line graph), was also introduced. 

The author then continued with another inequality, which is a result of the study of @chartrand69 as theorem 1.1; $\kappa^{'}(L(G))\geq 2\kappa^{'}(G)-2$ for a connected graph $G$. The thesis of the study is anchored on this inequality; whether a similar result will hold for essential edge connectivity and that a result similar to theorem 1.1 can be proven. The author introduced  $\kappa_{e}^{'}(G)$ to denote the essential edge connectivity of $G$, discussed some related concepts like when an edge cut $Y$ of $G$ is essential and when a graph $G$ is essentially k-edge-connected. The author also included 3 figures: graphs H, graph G and graphs G and L(G) respectively. He then pointed out an observation in figures 1 and 2 that essential edge connectivity of a graph can be equal to its edge connectivity and at some times they are not equal. He also discussed that letting $n\geq 1$ be an integer and that if the line graph of $G$ is a complete graph, then $G$ is $K_{1,n-1}$ or the complete graph with 3 vertices, $K_{3}$. These graphs have no essential edge cuts that is why these graphs are excluded in the study.

The author continued with proposition 1.2 given the above premises. The proposition states that 1) an essential edge cut must be an edge cut but not vice versa and that the essential edge connectivity of $G$ can be much larger than the edge connectivity of $G$, 2) The essential edge connectivity of $G$ is equal to the connectivity of the line graph of $G$, 3) the essential edge connectivity of the line graph of $G$ is greater than or equal to the essential edge connectivity of $G$ and 4) the connectivity of the line graph of $G$ is greater than or equal to the connectivity of $G$. The author also discussed justifications why these propositions hold.

The author then introduced theorem 1.3; the thesis of the study. It states that for graph $G$ that is not $K_{1,n-1}$ or $K_{3}$, and that if $G$ does not have a vertex that has a degree of two, then the essential edge connectivity of the line graph of $G$ is greater than or equal to two times the essential edge connectivity of $G$ minus two. The author thinks that theorem 1.3 can be proven using the concept of iterated line graph of $G$, $L^{k}(G)$, for $k=2,3,\ldots$, since according to @chartrand69, similar relationship holds between $\kappa(L^{2}(G))$ and $2\kappa(G)-2$. The author used this as corollary 1.4. He came up with corollary 1.5 by improving corollary 1.4. Corollary 1.5 states that a similar relationship holds between $\kappa(L^{2}(G))$ and $2\kappa(L(G))-2$. This ends the introduction.

In the preliminary results, considering the arguments discussed in the introduction with respect to theorem 1.3, the author proved and established proposition 2.1 stating that the degree sum of any two adjacent vertices is at least $\kappa_{e}^{'}(G)+2$. He then let $X$ be a minimal essential edge cut of $L(G)$ such that $|X|=\kappa_e^{'}(L(G))$ and used this to justify that $L_{1}$ and $L_{2}$ are the only two nontrivial components of $L(G)-X$. Using the definition of line graphs that $V(L(G))$ is a disjoint union of $V(L_{1})$ and $V(L_{2})$, he introduced $f:E(G)\mapsto \{1,2\}$; a 2-edge-coloring of $G$. Proposition 2.2 and 2.3 followed these arguments. Proposition 2.2 states that the $|V(L_{i})|\geq2$ and that two vertices $v_{e_{1}}$, $v_{e_{2}}$ $\in X$ if and only if $e_{1}$, $e_{2}$ $\in E(G)$ share a common vertex and $f(e_{1})\neq f(e_{2})$. Proposition 2.3 states for the set of bi-colored vertices of $G$, $V_{12}$, the following holds: 1) the degree of each vertex in $V_{12}$ is greater than or equal to two, 2) each vertex of $G-V_{12}$ is mono-colored in $G$ and for each component $H$ of $G-V_{12}$, all edges with at least one end in $H$ have the same color as the edges of $H$, 3) If $1 \leq |V_{12}|\leq 3$ and $V_{12}$ is not a vertex cut, then the subgraph of $G$ induced by $V_{12}$, $G[V_{12}]$, is connected, 4) if the number of vertices in $V_{12}=1$ or $2$, then $V_{12}$ is a vertex cut of $G$. He also defined $E_{i}(u)$ as the set of edges $e\in G$ incident to vertex $u\in G$ such that $f(e)=i$ for $i=1,2$. This was used in proposition 2.4 which follows from proposition 2.2 and its proof. Proposition 2.4 states that 1) $|X|=\sum_{u\in V_{12}}|E_{1}(u)|\cdot|E_{2}(u)|$, 2) for each $u\in V_{12}$ and $i=1,2$, $|E_{1}(u)|\cdot|E_{2}(u)|\geq d_{G}(u)-1$, 3) if for each $u\in V_{12}$ and $i=1,2$, $|E_{i}(u)|\geq 2$, then $|E_{1}(u)|\cdot|E_{2}(u)|\geq 2(d_{G}(u)-2)$.

The last part of the study is the proof of main theorem 1.3. The author started by proving the trivial cases in claims 1 through 4 then finished with the proof of claim 5. There are three cases for claim 4. In the first case, there are two subcases. In the third case, there are three subcases. The preliminary results discussed above where thoroughly used to prove these claims and theorem 1.3.

The first claim states that if $\kappa_{e}^{'}(G)=1$ or $2$, then $|X|\geq 2\kappa_{e}^{'}(G)-2$. The proof was easily established by substitution and by proposition 1.2. The second claim states that if $|V_{12}|\geq \kappa_{e}^{'}(G)-1$, then $|X|\geq 2\kappa_{e}^{'}(G)-2$. The proof to this claim was proven using substitution, the given that for each vertex $v_{i}\in V_{12}$, $d(v_{i})\geq 3$ and proposition 2.4. Claim 3 states that if $|V_{12}|=1$, then $|X|\geq 2\kappa_{e}^{'}(G)$. Proposition 2.2, 2.3 and 2.4 and claim 1 was used to prove this claim. The highlight of the proof is showing that $|X|\geq |E_1(v_1)|\cdot|E_2(v_1)|\geq|[\{v_1\},V(G_1)]|\geq 2\kappa_e^{'}(G)$ with the assumption that $V_{12}=\{v_1\}$ that led to the essential edge cut $[\{v_1\},V(G_1)]$. Another highlight in the proof is the assumption that $G_1$ is nontrivial. This assumption led to the conclusion that both $G_1$ and $G_2$ are the only two nontrivial components of $G-\{v_1\}$. Claim 4 states that if $G[V_{12}]$ contains at least two independent edges, then $|X|\geq 2\kappa_e^{'}(G)$. By assuming that $v_1,v_2,v_3,v_4\in V_{12}$ such that $v_1v_2\in E(G)$ and $v_3v_4\in E(G)$ and using proposition 2.1 and 2.4, the proof of claim 4 is completed.

To prove theorem 1.3, the author showed that $|X|\geq 2\kappa_{e}^{'}(G)-2$ for three cases: 1) $G-V_{12}$ is connected, 2) $V_{12}$ is a vertex cut such that $G-V_{12}$ contains two nontrivial components, 3) $V_{12}$ is a vertex cut such that $G-V_{12}$ contains at most one nontrivial component. In the first case, two subcases were considered: 1) $G[V_{12}]$ is isomorphic to $K_{1,t-1}$ such that $t=|V_{12}|\geq 2$ and 2) $G[V_{12}]$ is isomorphic to $K_3$. Results in considering subcase 1.1 and 1.2 proves $|X|\geq 2\kappa_{e}^{'}(G)-2$. The result $|X|\geq 2\kappa_{e}^{'}(G)+k-2\geq 2\kappa_{e}^{'}(G)-1$ for $k=3$ completed the proof of case 2. In the third case, three subcases were considered: 1) $|N_{G[V_{12}]}(W)|\geq 2$, 2) $V_{12}$ is a vertex cut such that all components of $G-V_{12}$ are trivial (i.e. $G-V_{12}=W$) and $|N_{G[V_{12}]}(W)|=1$ and 3) $V_{12}$ is a vertex cut such that $G-V_{12}$ contains exactly one none trivial component and $|N_{G[V_{12}]}(W)|=1$. Before considering these three subcases, the author let $\omega\geq 1$ be an integer and $W=\{w_1,w_2,\ldots,w_\omega\}$ be the union of all trivial components of $G-V_{12}$. In subcase 3.1, the author assumed that $N_{G[V_{12}]}(W)=\{v_{i_1},v_{i_2},\ldots,v_{i_s}\}$, for $s\geq2$. By letting $V_{12}-N_{G[V_{12}]}(W)=\{v_{i_{s+1}},v_{i_{s+2}},\ldots,v_{i_t}\}$, by proposition 2.1 and 2,4, by the definition that for each vertex $v_i\in V_{12}$, $d(v_i)\geq 3$, and by $\kappa_e^{'}(G)\geq 3$, the result $2\leq s\leq \kappa_e^{'}(G)-1$ proved $|X|\geq 2\kappa_e^{'}(G)-2$ if the vertices of the trivial components are adjacent to at least two vertices in $V_{12}$. Considering subcase 3.2 and 3.3, case 3 was assumed which led to another assumption; $|N_{G[V_{12}]}(W)|=1$. Considering case 3.2, the author assumed that $N_{G[V_{12}]}(W)=\{v_1\}$. By the assumption made earlier that $t=|V_{12}|\geq 2$ and $G[V_{12}]$ has at most one independent edge, results show that every vertex in $V_{12}-\{v_1\}$ have degree of at most 2, contrary to proposition 2.3. As a result, subcase 3.2 can be excluded. Considering subcase 3.3 the author let $G^{'}$ be the nontrivial component of $G-V_{12}$. By proposition 2.4, by the given and the by the previous assumptions, another assumption was induced; $E(G[V_{12}-\{v_1\}])$ is edgeless. This assumption plus the assumption that all edges in $[\{v_1\},V(G^{'})]$ have color 2 were used to prove claim 5.

Claim 5 states that $|E_1(v_1)|\geq 2$ and $|E_2(v_1)|\geq 2$. Both inequalities were proven by contradiction. Showing $|E_1(v_1)|\geq 2$, the author contradicted $|[\{v_1\},V(G^{'})]|\geq 2$ which led to a contradiction with $t=|V_{12}|\leq \kappa_e^{'}(G)-2$ and the completion of its proof. To show $|E_2(v_1)|\geq 2$, the author assumed $|V_{12}|=2$, $V_{12}=\{v_1,v_2\}$, $v_1v_2\in E(G)$ and $v_1,v_2$ have color 1. His argument led to a contradiction with proposition 2.2. He then assumed that $|V_{12}|\geq 3$ and claimed that for each $i\in \{2,3,\ldots,t\}$, $v_1,v_i\in E(G)$ and $v_1v_i$ has color 1. This again led to another contradiction completing the proof of claim 5.

Finally, he proved case 3 using proposition 2.4 with the result, $|X|\geq 2\kappa_e^{'}(G)-2$ where $|X|=\kappa_e^{'}(L(G))$. This concludes the proof of theorem 1.3 and the study followed by the list of references.

\pagebreak

# Insights, Stand, Reflection and Suggestions

The critiquing experience for this subject introduced me to new interesting concepts in graph theory especially the topic of connectivity. Connectivity is quite interesting since I learned that it tackles different important measures of vulnerability and fault-tolerance of networks [@cai19; @cheng20]. It is quite interesting and fascinating how scientist and mathematicians try to label graphs based on their connectedness. However, it is really difficult for me to understand more advanced network reliability indices such as super connectivity and super edge connectivity for super connected and super edge connected networks [@cai19], super extra edge connectivity for super extra edge-connected graphs [@cheng20], super $p$-restricted edge connectivity of line graphs [@lin09], and essential edge connectivity of line graphs [@shao18]. 

The study I critiqued focused on essential edge connectivity relations of a graph and its line graph rather than on vulnerability or fault-tolerance of a graph or a network. I chose the study I am critiquing because I thought it is the easiest to critique among the papers I read and cited above. Easy as it may seem, I have to learn and understand new concepts like induced subgraphs, bipartite graphs, line graphs and iterated line graphs, to mention but a few. I noticed in the articles I have read that it is common to introduce preliminary concepts with respect to the main topic of the study. This is really helpful and I appreciate it. But I also noticed that as the study develops, additional concepts that were not in the preliminaries are introduced without any preliminary basics (like some of the concepts I mentioned and one is the concept of edge coloring, which was introduced and used later in the study). This can make the reading and understanding of these articles really hard. It would be really nice if authors of these kind of articles consider adding preliminary basics along with these concepts when introducing them later in the study. I know its not a text book but at least it should discuss just the preliminary basics needed to understand it with respect to its use in the study. 

Another difficult thing in the study is the use of summation operations and composition of functions (notations over another notation over another notation). Here is an example of a composition of three functions in the study, $|N_{G[V_{12}]}(W)|=1$. In the example, sets and subgraphs are considered. To understand the article is really challenging. These are the hurdles I faced in this critiquing activity. Nonetheless, it was worth it to learn about these concepts and understand them in the context of the study. It really helped me have a general understanding of the study and the things I need to critique and most of all a general understanding of the study of connenctivity.

On the other hand, I really admire and appreciate the way the author indirectly introduced and defined the concept of essential edge connectivity. The definition can be hard to understand at first because of the indirect approach, but as I read through the article, I saw how the presentation (of defining the main concept -- essential edge connectivity -- of the study) is similar to the presentation of concepts he later introduced and used in the proof of the main theorem. With this, when I got to the difficult part of the study, I was already comfortable with his presentation of concepts and proofs. The author was also generous to include figures of a graph and its line graph. It gave me a concrete understanding of the concept of a line graph of a graph. I noticed some typographical errors like inconsistencies of periods after headings but all in all the article was excellent.

The result of the study is a theorem (theorem 1.3) and its proof, which is another addition to the literature of essential edge connectivity relations of a graph and its line graph. I noticed that the author only cited 5 references. This means that there is little literature on this topic. It would be really nice and novel to do research in this topic and contribute to its literature. 

# References