---
title: "R Notebook"
output: pdf_document
---


```{r}
v1 <- c(1, 2, 3)
v2 <- c(2, 3, 4)
(v1 > 0) || (v2 > 3)
```

\begin{table}[!h]
        \centering
        
\begin{tabular}{p{0.50\textwidth}p{0.50\textwidth}}
1. $\displaystyle x+1$ & 4. $\displaystyle x^{2}$ \\
2. $\displaystyle 2y-1$ & 5. $\displaystyle xxx$ \\
3. $\displaystyle 1+1$ & 6. $\displaystyle 2xy$ \\


\end{tabular}
        
        \end{table}
        
        
\begin{center}
$\displaystyle \begin{array}{ll}
&3481\\
\cline{2-2}
3 )\kern-0.7em&4444\\
&\kern-0.4em\begin{array}[t]{l}
\underline{3}\\
14\\
\underline{12\ \ }\\
\kern+0.53em 24\\
\kern+0.53em\underline{24\ }\\
\kern+1.58em 4\ \ \\
\kern+1.58em\underline{3}\\
\kern+1.58em 1
\end{array}
\end{array}$
\end{center}


\begin{gather*}
\begin{array}{ c c c }
! & \int ^{a}_{b} f'( x) dx=\underbrace{\overbrace{f( b) -f( a)}^{}}_{bvnbvnbvbnvnbvbnvbnvnvn} & \underbrace{\frac{1}{4} W_{\mu \nu } \cdot W^{\mu \nu } -\frac{1}{4} B_{\mu \nu } B^{\mu \nu } -\frac{1}{4} G^{a}_{\mu \nu } G^{\mu \nu }_{a}}_{\mathrm{kinetic\ energies\ and\ self-interactions\ of\ the\ gauge\ bosons}}\\
 & \Vert x+y\Vert \geq \overbrace{\bigl|\Vert x\Vert -\Vert y\Vert \bigr|}^{\mathrm{ordinate}} & \nabla \cdot \mathbf{D} =\rho \ \mathrm{and} \ \nabla \cdot \mathbf{B} =0\ \\
 &  & \nabla \times \mathbf{E} =-\frac{\partial \mathbf{B}}{\partial t} \ \mathrm{and} \ \nabla \times \mathbf{H} =\mathbf{J} +\frac{\partial \mathbf{D}}{\partial t}\\
 & y=\frac{\sum\limits _{i} w_{i} y_{i}}{\sum\limits _{i} w_{i}} \ \ ,i=1,2...k & e=\lim\limits _{n\rightarrow \infty }\left( 1+\frac{1}{n}\right)^{n}\\
 &  & 
\end{array}\\
\dot{x}_{i} =a_{i} x_{i'} -( d+a_{i0} +a_{i1}) x_{i} +rx_{i}( f_{i} -\phi )
\end{gather*}